openapi: 3.0.0
info:
  title: Smart Donor Matching API
  description: API for blood donation and recipient matching.
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
paths:
  /recipients/match-donors:
    post:
      summary: Match blood donors to recipients
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                recipientBloodType:
                  type: string
                  example: A+
                city:
                  type: string
                  example: Hyderabad
      responses:
        '200':
          description: A list of matching donors
          content:
            application/json:
              schema:
                type: object
                properties:
                  donors:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: Test Donor
                        bloodType:
                          type: string
                          example: A+
                        city:
                          type: string
                          example: Hyderabad
  /blood/expiry:
    post:
      summary: Predict the expiry date of donated blood
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                donationDate:
                  type: string
                  example: '2025-05-08'
      responses:
        '200':
          description: Expiry date for the blood
          content:
            application/json:
              schema:
                type: object
                properties:
                  donationDate:
                    type: string
                    example: '2025-05-08'
                  expiryDate:
                    type: string
                    example: '2025-06-19'
